[package]
name = "parsec-service"
version = "0.6.0"
authors = ["Anton Antonov <anton.antonov@arm.com>",
           "Paul Howard <paul.howard@arm.com>",
           "Ionut Mihalcea <ionut.mihalcea@arm.com>",
           "Hugues de Valon <hugues.devalon@arm.com>"]
description = "A language-agnostic API to secure services in a platform-agnostic way"
license = "Apache-2.0"
repository = "https://github.com/parallaxsecond/parsec"
readme = "README.md"
keywords = ["security", "service"]
categories = ["cryptography", "hardware-support"]
edition = "2018"

[[bin]]
name = "parsec"
path = "src/bin/main.rs"

[dependencies]
parsec-interface = "0.23.0"
rand = { version = "0.8.2", features = ["small_rng"], optional = true }
base64 = "0.13.0"
uuid = "0.8.1"
threadpool = "1.8.1"
signal-hook = "0.3.4"
sd-notify = "0.1.1"
toml = "0.5.6"
serde = { version = "1.0.115", features = ["derive"] }
env_logger = "0.8.2"
log = { version = "0.4.11", features = ["serde"] }
pkcs11 = { version = "0.5.0", optional = true }
picky-asn1-der = { version = "0.2.4", optional = true }
picky-asn1 = { version = "0.3.0", optional = true }
tss-esapi = { version = "4.0.10-alpha.2", optional = true }
bincode = "1.3.1"
structopt = "0.3.17"
derivative = "2.1.1"
version = "3.0.0"
hex = { version = "0.4.2", optional = true }
psa-crypto = { version = "0.7.0", default-features = false, features = ["operations"], optional = true }
zeroize = { version = "1.1.0", features = ["zeroize_derive"] }
picky-asn1-x509 = { version = "0.4.0", optional = true }
users = "0.11.0"
libc = "0.2.77"
anyhow = "1.0.32"
# Using a fork until the JWT support is merged into the main rust-spiffe repository
spiffe = { git = "https://github.com/hug-dev/rust-spiffe", branch = "refactor-jwt", optional = true }
rust-cryptoauthlib = { version = "0.1.0", optional = true }

[dev-dependencies]
rand = { version = "0.8.2", features = ["small_rng"] }

[package.metadata.docs.rs]
features = ["pkcs11-provider", "tpm-provider", "tss-esapi/docs", "mbed-crypto-provider", "cryptoauthlib-provider"]

[features]
default = ["unix-peer-credentials-authenticator"]

# Providers
mbed-crypto-provider = ["psa-crypto"]
pkcs11-provider = ["pkcs11", "picky-asn1-der", "picky-asn1", "picky-asn1-x509", "psa-crypto", "rand"]
tpm-provider = ["tss-esapi", "picky-asn1-der", "picky-asn1", "picky-asn1-x509", "hex"]
cryptoauthlib-provider = ["rust-cryptoauthlib"]
all-providers = ["tpm-provider", "pkcs11-provider", "mbed-crypto-provider", "cryptoauthlib-provider"]

# Authenticators
direct-authenticator = []
unix-peer-credentials-authenticator = []
jwt-svid-authenticator = ["spiffe"]
all-authenticators = ["direct-authenticator", "unix-peer-credentials-authenticator", "jwt-svid-authenticator"]
