#########################################################################
# The example config file for atecc608a cryptochip.
# There must be an I2C bus with a cryptochip soldered, otherwise provider 
# instantiation fails.
# Not to be used by github CI.
#########################################################################
[core_settings]
# The CI already timestamps the logs
log_timestamp = false
log_error_details = true

# The container runs the Parsec service as root, so make sure we disable root
# checks.
allow_root = true

[listener]
listener_type = "DomainSocket"
timeout = 200 # in milliseconds
socket_path = "/tmp/parsec.sock"

[authenticator]
auth_type = "Direct"

[[key_manager]]
name = "on-disk-manager"
manager_type = "OnDisk"
store_path = "./mappings"

[[provider]]
provider_type = "CryptoAuthLib"
key_info_manager = "on-disk-manager"
device_type = "atecc608a"
iface_type = "i2c"
wake_delay = 1600
rx_retries = 20
# i2c parameters for i2c-pseudo proxy
slave_address = 0xc0
bus = 1
baud = 400000
