[core_settings]
# The CI already timestamps the logs
log_timestamp = false
log_error_details = true

[listener]
listener_type = "DomainSocket"
# The timeout needs to be smaller than the test client timeout (five seconds) as it is testing
# that the service does not hang for very big values of body or authentication length.
timeout = 3000 # in milliseconds

[[key_manager]]
name = "on-disk-manager"
manager_type = "OnDisk"

[[provider]]
provider_type = "Tpm"
key_info_manager = "on-disk-manager"
tcti = "mssim"
owner_hierarchy_auth = "hex:74706d5f70617373" # "tpm_pass" in hex
